# Generated by Django 2.2 on 2020-07-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='info',
            name='updated_at',
        ),
    ]
