# Generated by Django 2.2 on 2020-07-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20200714_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='googleMapsLink',
            field=models.TextField(default='https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3995.242123767053!2d-17.450418873410932!3d14.704142033889514!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x55899975fc4381f8!2sImmeuble%20Marega%20Zone%20A%20Grand%20Dakar%20www.dial221.com!5e0!3m2!1sfr!2ssn!4v1594743273319!5m2!1sfr!2ssn'),
            preserve_default=False,
        ),
    ]
